-- MySQL Script generated by MySQL Workbench
-- 01/27/17 16:18:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yii2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema yii2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yii2` DEFAULT CHARACTER SET utf8 ;
USE `yii2` ;

-- -----------------------------------------------------
-- Table `yii2`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2`.`user` (
  `id` INT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `auth_key` VARCHAR(32) NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `password_reset_token` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `status` SMALLINT NULL,
  `created_at` INT NULL,
  `updated_at` INT NULL,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2`.`Slide`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2`.`Slide` (
  `idSlide` INT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(500) NULL,
  `Imagen` VARCHAR(45) NULL,
  `Titulo2` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idSlide`, `user_id`),
  INDEX `fk_Slide_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Slide_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yii2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2`.`CategoriaEspecialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2`.`CategoriaEspecialidad` (
  `idCategoriaEspecialidad` INT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoriaEspecialidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2`.`TipoEspecialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2`.`TipoEspecialidad` (
  `idTipoEspecialidad` INT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoEspecialidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2`.`Especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2`.`Especialidad` (
  `idEspecialidades` INT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(255) NULL,
  `Visitas` INT NULL,
  `user_id` INT NOT NULL,
  `CategoriaEspecialidad_idCategoriaEspecialidad` INT NOT NULL,
  `TipoEspecialidad_idTipoEspecialidad` INT NOT NULL,
  PRIMARY KEY (`idEspecialidades`, `user_id`, `CategoriaEspecialidad_idCategoriaEspecialidad`, `TipoEspecialidad_idTipoEspecialidad`),
  INDEX `fk_Especialidad_Usuario1_idx` (`user_id` ASC),
  INDEX `fk_Especialidad_CategoriaEspecialidad1_idx` (`CategoriaEspecialidad_idCategoriaEspecialidad` ASC),
  INDEX `fk_Especialidad_TipoEspecialidad1_idx` (`TipoEspecialidad_idTipoEspecialidad` ASC),
  CONSTRAINT `fk_Especialidad_Usuario1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yii2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Especialidad_CategoriaEspecialidad1`
    FOREIGN KEY (`CategoriaEspecialidad_idCategoriaEspecialidad`)
    REFERENCES `yii2`.`CategoriaEspecialidad` (`idCategoriaEspecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Especialidad_TipoEspecialidad1`
    FOREIGN KEY (`TipoEspecialidad_idTipoEspecialidad`)
    REFERENCES `yii2`.`TipoEspecialidad` (`idTipoEspecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2`.`ComentarioEspecialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2`.`ComentarioEspecialidad` (
  `idComentarioEspecialidad` INT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(255) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Especialidad_idEspecialidades` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idComentarioEspecialidad`, `Especialidad_idEspecialidades`, `user_id`),
  INDEX `fk_ComentarioEspecialidad_Especialidad1_idx` (`Especialidad_idEspecialidades` ASC),
  INDEX `fk_ComentarioEspecialidad_Usuario1_idx` (`user_id` ASC),
  CONSTRAINT `fk_ComentarioEspecialidad_Especialidad1`
    FOREIGN KEY (`Especialidad_idEspecialidades`)
    REFERENCES `yii2`.`Especialidad` (`idEspecialidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ComentarioEspecialidad_Usuario1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yii2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2`.`Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2`.`Proyecto` (
  `idProyecto` INT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(255) NULL,
  `Url` VARCHAR(100) NULL,
  `Imagen` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  `Fecha` DATETIME NOT NULL,
  PRIMARY KEY (`idProyecto`, `user_id`),
  INDEX `fk_Proyecto_Usuario1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Proyecto_Usuario1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yii2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2`.`ComentarioProyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2`.`ComentarioProyecto` (
  `idComentarioProyecto` INT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(255) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Proyecto_idProyecto` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idComentarioProyecto`, `Proyecto_idProyecto`, `user_id`),
  INDEX `fk_ComentarioProyecto_Proyecto1_idx` (`Proyecto_idProyecto` ASC),
  INDEX `fk_ComentarioProyecto_Usuario1_idx` (`user_id` ASC),
  CONSTRAINT `fk_ComentarioProyecto_Proyecto1`
    FOREIGN KEY (`Proyecto_idProyecto`)
    REFERENCES `yii2`.`Proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ComentarioProyecto_Usuario1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yii2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2`.`noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2`.`noticia` (
  `idnoticia` INT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(255) NULL,
  `imagen` VARCHAR(45) NULL,
  `visitas` INT NULL,
  `user_id` INT NOT NULL,
  `link` VARCHAR(255) NULL,
  PRIMARY KEY (`idnoticia`, `user_id`),
  INDEX `fk_noticia_Usuario1_idx` (`user_id` ASC),
  CONSTRAINT `fk_noticia_Usuario1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yii2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2`.`comentarioNoticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2`.`comentarioNoticia` (
  `idcomentarioNoticia` INT NULL AUTO_INCREMENT,
  `noticia_idnoticia` INT NOT NULL,
  `user_id` INT NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  PRIMARY KEY (`idcomentarioNoticia`, `noticia_idnoticia`, `user_id`),
  INDEX `fk_comentarioNoticia_noticia1_idx` (`noticia_idnoticia` ASC),
  INDEX `fk_comentarioNoticia_Usuario1_idx` (`user_id` ASC),
  CONSTRAINT `fk_comentarioNoticia_noticia1`
    FOREIGN KEY (`noticia_idnoticia`)
    REFERENCES `yii2`.`noticia` (`idnoticia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarioNoticia_Usuario1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yii2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2`.`contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2`.`contacto` (
  `idcontacto` INT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `leido` TINYINT(1) NULL,
  `user_id` INT NOT NULL,
  `mensaje` VARCHAR(255) NULL,
  PRIMARY KEY (`idcontacto`, `user_id`),
  INDEX `fk_contacto_Usuario1_idx` (`user_id` ASC),
  CONSTRAINT `fk_contacto_Usuario1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yii2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2`.`evento` (
  `idevento` INT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(255) NULL,
  `imagen` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `hora_inicio` TIME(3) NULL,
  `hora_fin` TIME(3) NULL,
  `lugar` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idevento`, `user_id`),
  INDEX `fk_evento_Usuario1_idx` (`user_id` ASC),
  CONSTRAINT `fk_evento_Usuario1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yii2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2`.`ratingEspecialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2`.`ratingEspecialidad` (
  `idRatingEspecialidad` INT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `Especialidad_idEspecialidades` INT NOT NULL,
  `Rating` FLOAT NULL DEFAULT 0,
  PRIMARY KEY (`idRatingEspecialidad`, `user_id`, `Especialidad_idEspecialidades`),
  INDEX `fk_ratingEspecialidad_Usuario1_idx` (`user_id` ASC),
  INDEX `fk_ratingEspecialidad_Especialidad1_idx` (`Especialidad_idEspecialidades` ASC),
  CONSTRAINT `fk_ratingEspecialidad_Usuario1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yii2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ratingEspecialidad_Especialidad1`
    FOREIGN KEY (`Especialidad_idEspecialidades`)
    REFERENCES `yii2`.`Especialidad` (`idEspecialidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2`.`ratingProyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2`.`ratingProyecto` (
  `idRatingProyecto` INT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `Proyecto_idProyecto` INT NOT NULL,
  `Rating` FLOAT NULL DEFAULT 0,
  PRIMARY KEY (`idRatingProyecto`, `user_id`, `Proyecto_idProyecto`),
  INDEX `fk_ratingProyecto_Usuario1_idx` (`user_id` ASC),
  INDEX `fk_ratingProyecto_Proyecto1_idx` (`Proyecto_idProyecto` ASC),
  CONSTRAINT `fk_ratingProyecto_Usuario1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yii2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ratingProyecto_Proyecto1`
    FOREIGN KEY (`Proyecto_idProyecto`)
    REFERENCES `yii2`.`Proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2`.`Maestro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2`.`Maestro` (
  `idMaestro` INT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `tipo` VARCHAR(45) NULL,
  `imagen` VARCHAR(100) NULL,
  `descripcion` VARCHAR(255) NULL,
  `linkFace` VARCHAR(100) NULL,
  `linkTwitter` VARCHAR(100) NULL,
  `linkGoogle` VARCHAR(100) NULL,
  `linkInstagram` VARCHAR(100) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idMaestro`, `user_id`),
  INDEX `fk_Maestro_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Maestro_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yii2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2`.`Experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2`.`Experiencia` (
  `idExperiencia` INT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `valor` INT NULL DEFAULT 0,
  `user_id` INT NOT NULL,
  `orientacion` INT NULL DEFAULT 0,
  PRIMARY KEY (`idExperiencia`, `user_id`),
  INDEX `fk_Experiencia_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Experiencia_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yii2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2`.`PaginaEnlaces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2`.`PaginaEnlaces` (
  `idEnlaces` INT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `link` VARCHAR(255) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idEnlaces`, `user_id`),
  INDEX `fk_PaginaEnlaces_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_PaginaEnlaces_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yii2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2`.`PaginaContacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2`.`PaginaContacto` (
  `idPaginaContacto` INT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `direccion` VARCHAR(100) NULL,
  `faceLink` VARCHAR(100) NULL,
  `rssLink` VARCHAR(100) NULL,
  `googleLink` VARCHAR(100) NULL,
  `pintLink` VARCHAR(100) NULL,
  `instagramLink` VARCHAR(100) NULL,
  `user_id` INT NOT NULL,
  `paginaWeb` VARCHAR(100) NULL,
  `PiePagina` VARCHAR(255) NULL,
  PRIMARY KEY (`idPaginaContacto`, `user_id`),
  INDEX `fk_PaginaContacto_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_PaginaContacto_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yii2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2`.`PaginaInicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2`.`PaginaInicio` (
  `idPaginaInicio` INT NULL AUTO_INCREMENT,
  `tituloPortada` VARCHAR(100) NOT NULL,
  `descripcionPortada` VARCHAR(500) NOT NULL,
  `cantidadAlumnos` INT NOT NULL,
  `cantidadPremios` INT NOT NULL,
  `imagenAlumnos` VARCHAR(100) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idPaginaInicio`, `user_id`),
  INDEX `fk_PaginaInicio_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_PaginaInicio_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yii2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2`.`PaginaNosotros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2`.`PaginaNosotros` (
  `idPaginaNosotros` INT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(800) NULL,
  `imagen` VARCHAR(100) NOT NULL,
  `user_id` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `descripcion2` VARCHAR(800) NULL,
  PRIMARY KEY (`idPaginaNosotros`, `user_id`),
  INDEX `fk_PaginaNosotros_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_PaginaNosotros_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yii2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2`.`ComentarioAlumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2`.`ComentarioAlumno` (
  `idComentarioAlumno` INT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(255) NOT NULL,
  `user_id` INT NOT NULL,
  `Fecha` DATETIME NOT NULL,
  PRIMARY KEY (`idComentarioAlumno`, `user_id`),
  INDEX `fk_ComentarioAlumno_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_ComentarioAlumno_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yii2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2`.`PaginaImagenPortada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2`.`PaginaImagenPortada` (
  `idPaginaImagenPortada` INT NULL AUTO_INCREMENT,
  `imagen` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idPaginaImagenPortada`, `user_id`),
  INDEX `fk_PaginaImagenPortada_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_PaginaImagenPortada_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yii2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii2`.`IncisoNosotros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2`.`IncisoNosotros` (
  `idIncisoNosotros` INT NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `PaginaNosotros_idPaginaNosotros` INT NOT NULL,
  PRIMARY KEY (`idIncisoNosotros`, `PaginaNosotros_idPaginaNosotros`),
  INDEX `fk_IncisoNosotros_PaginaNosotros1_idx` (`PaginaNosotros_idPaginaNosotros` ASC),
  CONSTRAINT `fk_IncisoNosotros_PaginaNosotros1`
    FOREIGN KEY (`PaginaNosotros_idPaginaNosotros`)
    REFERENCES `yii2`.`PaginaNosotros` (`idPaginaNosotros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `yii2`.`Slide`
-- -----------------------------------------------------
START TRANSACTION;
USE `yii2`;
INSERT INTO `yii2`.`Slide` (`idSlide`, `Titulo`, `Descripcion`, `Imagen`, `Titulo2`, `user_id`) VALUES (1, 'Education Needs', 'There are many variations of passages of Lorem Ipsum available, but the majority have<br>suffered alteration in some form, by injected humour, or randomised words which<br>don\'t look even slightly believable.', '1.jpg', 'Complete Solution', 1);
INSERT INTO `yii2`.`Slide` (`idSlide`, `Titulo`, `Descripcion`, `Imagen`, `Titulo2`, `user_id`) VALUES (2, 'Education Needs', 'There are many variations of passages of Lorem Ipsum available, but the majority have<br>suffered alteration in some form, by injected humour, or randomised words which<br>don\'t look even slightly believable.', '4.jpg', 'Complete Solution', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `yii2`.`Maestro`
-- -----------------------------------------------------
START TRANSACTION;
USE `yii2`;
INSERT INTO `yii2`.`Maestro` (`idMaestro`, `nombre`, `tipo`, `imagen`, `descripcion`, `linkFace`, `linkTwitter`, `linkGoogle`, `linkInstagram`, `user_id`) VALUES (1, 'Louis Smith', 'Teacher', '1.png', 'There are many variaons of passa of Lorem Ipsuable, amrn in sofby injected humour, amr', NULL, NULL, NULL, NULL, 1);
INSERT INTO `yii2`.`Maestro` (`idMaestro`, `nombre`, `tipo`, `imagen`, `descripcion`, `linkFace`, `linkTwitter`, `linkGoogle`, `linkInstagram`, `user_id`) VALUES (2, 'Louis Smith', 'Teacher', 'l-2.jpg', 'There are many variaons of passa of Lorem Ipsuable, amrn in sofby injected humour, amr', NULL, NULL, NULL, NULL, 1);
INSERT INTO `yii2`.`Maestro` (`idMaestro`, `nombre`, `tipo`, `imagen`, `descripcion`, `linkFace`, `linkTwitter`, `linkGoogle`, `linkInstagram`, `user_id`) VALUES (3, 'Louis Smith', 'Teacher', 'l-2.jpg', 'There are many variaons of passa of Lorem Ipsuable, amrn in sofby injected humour, amr', NULL, NULL, NULL, NULL, 1);
INSERT INTO `yii2`.`Maestro` (`idMaestro`, `nombre`, `tipo`, `imagen`, `descripcion`, `linkFace`, `linkTwitter`, `linkGoogle`, `linkInstagram`, `user_id`) VALUES (4, 'Louis Smith', 'Teacher', 'l-2.jpg', 'There are many variaons of passa of Lorem Ipsuable, amrn in sofby injected humour, amr', NULL, NULL, NULL, NULL, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `yii2`.`Experiencia`
-- -----------------------------------------------------
START TRANSACTION;
USE `yii2`;
INSERT INTO `yii2`.`Experiencia` (`idExperiencia`, `descripcion`, `valor`, `user_id`, `orientacion`) VALUES (1, 'Programming', 80, 1, 0);
INSERT INTO `yii2`.`Experiencia` (`idExperiencia`, `descripcion`, `valor`, `user_id`, `orientacion`) VALUES (2, 'Programming', 75, 1, 1);
INSERT INTO `yii2`.`Experiencia` (`idExperiencia`, `descripcion`, `valor`, `user_id`, `orientacion`) VALUES (3, 'Designing', 75, 1, 0);
INSERT INTO `yii2`.`Experiencia` (`idExperiencia`, `descripcion`, `valor`, `user_id`, `orientacion`) VALUES (4, 'Creative Writing', 90, 1, 0);
INSERT INTO `yii2`.`Experiencia` (`idExperiencia`, `descripcion`, `valor`, `user_id`, `orientacion`) VALUES (5, 'Designing', 80, 1, 1);
INSERT INTO `yii2`.`Experiencia` (`idExperiencia`, `descripcion`, `valor`, `user_id`, `orientacion`) VALUES (6, 'English Lessons', 70, 1, 0);
INSERT INTO `yii2`.`Experiencia` (`idExperiencia`, `descripcion`, `valor`, `user_id`, `orientacion`) VALUES (7, 'English Lessons', 100, 1, 1);
INSERT INTO `yii2`.`Experiencia` (`idExperiencia`, `descripcion`, `valor`, `user_id`, `orientacion`) VALUES (8, 'Creative Writing', 90, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `yii2`.`PaginaEnlaces`
-- -----------------------------------------------------
START TRANSACTION;
USE `yii2`;
INSERT INTO `yii2`.`PaginaEnlaces` (`idEnlaces`, `titulo`, `link`, `user_id`) VALUES (1, 'Teachers & Staff', NULL, 1);
INSERT INTO `yii2`.`PaginaEnlaces` (`idEnlaces`, `titulo`, `link`, `user_id`) VALUES (2, 'Our Courses', NULL, 1);
INSERT INTO `yii2`.`PaginaEnlaces` (`idEnlaces`, `titulo`, `link`, `user_id`) VALUES (3, 'Courses Categories', NULL, 1);
INSERT INTO `yii2`.`PaginaEnlaces` (`idEnlaces`, `titulo`, `link`, `user_id`) VALUES (4, 'Support', NULL, 1);
INSERT INTO `yii2`.`PaginaEnlaces` (`idEnlaces`, `titulo`, `link`, `user_id`) VALUES (5, 'Terms & Conditions', NULL, 1);
INSERT INTO `yii2`.`PaginaEnlaces` (`idEnlaces`, `titulo`, `link`, `user_id`) VALUES (6, 'Privacy Policy', NULL, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `yii2`.`PaginaContacto`
-- -----------------------------------------------------
START TRANSACTION;
USE `yii2`;
INSERT INTO `yii2`.`PaginaContacto` (`idPaginaContacto`, `telefono`, `correo`, `direccion`, `faceLink`, `rssLink`, `googleLink`, `pintLink`, `instagramLink`, `user_id`, `paginaWeb`, `PiePagina`) VALUES (1, '+88 018 785 4589', 'devitems@email.com', 'ur address goes here,street.', NULL, NULL, NULL, NULL, NULL, 1, 'www.devitems.com', 'There are many variations of passg of Lorem Ipsum available, but thmajority have suffered altem.');

COMMIT;


-- -----------------------------------------------------
-- Data for table `yii2`.`PaginaInicio`
-- -----------------------------------------------------
START TRANSACTION;
USE `yii2`;
INSERT INTO `yii2`.`PaginaInicio` (`idPaginaInicio`, `tituloPortada`, `descripcionPortada`, `cantidadAlumnos`, `cantidadPremios`, `imagenAlumnos`, `user_id`) VALUES (1, '¿ PORQUÉ UPIIZ ?', 'La carrera de <b>Ingeniería en Sistemas Computacionales</b> pertenece a la Unidad Profesional Interdisciplinaria de Ingeniería Campus Zacatecas (UPIIZ) del Instituto Politécnico Nacional (IPN). El IPN ocupa el tercer lugar a nivel nacional como mejor universidad.</p><p>El IPN te ofrece beca desde el primer semestre, movilidad internacional, asistencia a eventos como Campus Party, concursos de programación, certificaciones, cursos extracurriculares y mucho más.</p>', 700, 5, '3.jpg', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `yii2`.`PaginaNosotros`
-- -----------------------------------------------------
START TRANSACTION;
USE `yii2`;
INSERT INTO `yii2`.`PaginaNosotros` (`idPaginaNosotros`, `descripcion`, `imagen`, `user_id`, `titulo`, `descripcion2`) VALUES (1, 'come with us, we also teach children about the basic values of human beings as honesty, kindness, generosity, courage, freedom, equality and respect. Learn to celebrate diversity in a spirit of understanding and tolerance and develop a positive regard and awareness of other people. They are taught the values and responsibilities needed to become active members of the community, tolerance and develop something which the modern world is desperate for norem ipsum dolor sit amet desperate.', '6.jpg', 1, 'Well come to Educat', 'Snos trud exerci tation ullorper suscipit lobo maeisrn roester maeoirqs iserrtis nisl ut aliq poerwse thesr oper balinp asein hoinws mawsoib equat. Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more tolerance and develop obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through makin of the word in classical literature.');

COMMIT;


-- -----------------------------------------------------
-- Data for table `yii2`.`PaginaImagenPortada`
-- -----------------------------------------------------
START TRANSACTION;
USE `yii2`;
INSERT INTO `yii2`.`PaginaImagenPortada` (`idPaginaImagenPortada`, `imagen`, `descripcion`, `user_id`) VALUES (1, '1.jpg', 'INICIO', 1);
INSERT INTO `yii2`.`PaginaImagenPortada` (`idPaginaImagenPortada`, `imagen`, `descripcion`, `user_id`) VALUES (2, '4.jpg', 'NOSOTROS', 1);
INSERT INTO `yii2`.`PaginaImagenPortada` (`idPaginaImagenPortada`, `imagen`, `descripcion`, `user_id`) VALUES (3, '4.jpg', 'ESPECIALIDADES', 1);
INSERT INTO `yii2`.`PaginaImagenPortada` (`idPaginaImagenPortada`, `imagen`, `descripcion`, `user_id`) VALUES (4, '4.jpg', 'PROYECTOS', 1);
INSERT INTO `yii2`.`PaginaImagenPortada` (`idPaginaImagenPortada`, `imagen`, `descripcion`, `user_id`) VALUES (5, '4.jpg', 'NOTICIAS', 1);
INSERT INTO `yii2`.`PaginaImagenPortada` (`idPaginaImagenPortada`, `imagen`, `descripcion`, `user_id`) VALUES (6, '4.jpg', 'EVENTOS', 1);
INSERT INTO `yii2`.`PaginaImagenPortada` (`idPaginaImagenPortada`, `imagen`, `descripcion`, `user_id`) VALUES (7, '4.jpg', 'CONTACTO', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `yii2`.`IncisoNosotros`
-- -----------------------------------------------------
START TRANSACTION;
USE `yii2`;
INSERT INTO `yii2`.`IncisoNosotros` (`idIncisoNosotros`, `descripcion`, `PaginaNosotros_idPaginaNosotros`) VALUES (1, 'Nam gravida magna vitae ante dignissim', 1);
INSERT INTO `yii2`.`IncisoNosotros` (`idIncisoNosotros`, `descripcion`, `PaginaNosotros_idPaginaNosotros`) VALUES (2, 'Duis rhoncus lectus at velit hendrerit quis', 1);
INSERT INTO `yii2`.`IncisoNosotros` (`idIncisoNosotros`, `descripcion`, `PaginaNosotros_idPaginaNosotros`) VALUES (3, 'Sed fringilla tempor arcu feugiat risus', 1);
INSERT INTO `yii2`.`IncisoNosotros` (`idIncisoNosotros`, `descripcion`, `PaginaNosotros_idPaginaNosotros`) VALUES (4, 'Vivamus semper odio in nibh ultricies', 1);

COMMIT;

